### ISSUE TITLE
CoonsPatchMesh and photo image black

### ISSUE THREAD

**Issue by hdxpmc** [dmester/pdftosvg.net#10]
Hello
we have tested the pdf file for CoonsPatchMesh.
CoonsPatchMesh file: [meshgradient.pdf](https://github.com/dmester/pdftosvg.net/files/12427524/meshgradient.pdf)
it is black at the area of CoonsPatchMesh

**Comment by dmester** [comment]
Hello,
Thanks for reporting these issues. 

Only radial and axial gradients are currently supported. Other gradients are not trivial to convert since they are not natively supported by SVG. It is on my internal task list to look at more gradient types, but they are currently not prioritized.

Regarding the second file, it is using the pattern feature in PDF. It is planned for one of the upcoming releases.

Could you create a second issue and move one of the files to the other issue so that they can be handled separately?

**Comment by hdxpmc** [comment]
Hello,
Would you like to provide the callback for all element not supported ? and we can render it other way as image/pdfjs canvas/...

**Comment by dmester** [comment]
Support for all gradients have been added to PdfToSvg.NET version 1.1.0, so this test file should now render correctly.

Commit 3dc2e0e422251
