### ISSUE TITLE
How to save PdfPage to pdf file ?

### ISSUE THREAD

**Issue by hdxpmc** [dmester/pdftosvg.net#21]
Hello,
We need to pass single pdf page to other lib to extract html, We want to have each pdf page in each pdf file.
How to save the PdfPage to pdf file (1 page for one pdf file) ? 
Would you like to make MediaBox Property public ?

Best regards

**Comment by dmester** [comment]
Hello,

Thanks for your suggestion, but since the purpose of this library is to convert PDF files to SVG, I would recommend having a look at a general purpose PDF library instead. 

[PdfSharp](https://www.pdfsharp.net/) is a really good library for .NET that should be able to extract pages from a PDF document. You can find an example here:
	
https://www.pdfsharp.net/wiki/splitdocument-sample.ashx
