### ISSUE TITLE
Obfuscation of map text

### ISSUE THREAD

**Issue by PJTraut** [dmester/pdftosvg.net#25]
[CLEAR_NT_MAPS_Tok-Pisin_02-cropped.pdf](https://github.com/dmester/pdftosvg.net/files/14848303/CLEAR_NT_MAPS_Tok-Pisin_02-cropped.pdf)
![CLEAR_NT_MAPS_Tok-Pisin_02-1](https://github.com/dmester/pdftosvg.net/assets/90978900/4a94f9c3-db83-4308-8e90-cade61b843fd)

I am using the command line converter. Why are some text obfuscated and other not? Can this be disabled?

L1929: <text x="272.0244" y="288.8168">Dekapolis</text>
L1939: <text transform="matrix(1 0 0 1.1111 409.9651 573.3125)" class="txN3DEq">K</text>

Thanks for an awesome tool!

**Comment by dmester** [comment]
Text is not embedded as plain text in PDF documents, but encoded using character codes. PDF documents also include:

* A mapping from character codes to glyphs in the font.

* Optionally a mapping from character codes to Unicode characters.

PdfToSvg.NET will try to recreate text as far as possible using the Unicode mapping, but in some cases this is not possible, usually if multiple character codes are mapped to different font glyphs but to the same Unicode character. PdfToSvg.NET will in those cases remap the duplicate characters to characters in the [Private Use Area](https://en.wikipedia.org/wiki/Private_Use_Areas), which you can see in your case. This is done to ensure the text appear visually correct when displaying the SVG.

In this PDF the small caps in `Dᴇᴋᴀᴘᴏʟɪs` are mapped to ordinary lower case characters `Dekapolis`. This means those letters cannot be reused for ordinary lower case characters, because then those would visually appear as small caps when opening the SVG.

If you are converting the PDF for text extraction, you can specify [`FontResolver.LocalFonts`](https://pdftosvg.net/api/T_PdfToSvg_FontResolver#example) when converting the PDF. This option is currently only available in the API. When local fonts are used, PdfToSvg.NET will focus on extracting readable text instead of producing visually accurate results.

Example:
```cs
var conversionOptions = new SvgConversionOptions
{
    FontResolver = FontResolver.LocalFonts,
};

using (var doc = PdfDocument.Open("input.pdf"))
{
    var pageIndex = 0;

    foreach (var page in doc.Pages)
    {
        page.SaveAsSvg($"output-{pageIndex++}.svg", conversionOptions);
    }
}
```
