### ISSUE TITLE
Conversion error on a specific page

### ISSUE THREAD

**Issue by mmettey** [dmester/pdftosvg.net#28]
Hi,

I am having an issue to convert a specific PDF file in SVG, especially for one page. I use the latest version of your library (1.3.0).

Concerned file : 
[essai.pdf](https://github.com/dmester/pdftosvg.net/files/15274966/essai.pdf)

Command used :
pdftosvg.exe essai.pdf

Thanks in advance for your kind help.
Let me know if I can provide more information.

**Comment by dmester** [comment]
Thanks for reporting these PDF files!

This one turned out to be a bit tricky. PDF pages may contain inline images, without any length specified, only terminated with the two letters `"EI"`. Since those two letters can occur naturally in image data, PDF readers must resort to heuristics to decide where the image data ends and the page continues. PdfToSvg.NET previously verified `"EI"` was surrounded by whitespace, but in this particular file, the compressed image data itself satisfied those conditions.

I have improved the heuristics in 1.3.1, so the specified file and similar files can be parsed by the library.
