### ISSUE TITLE
Issue with rotated text

### ISSUE THREAD

**Issue by gentledepp** [dmester/pdftosvg.net#5]
Hello @dmester  
unfortunately, we do have another document that is converted, but seemingly errorneous or just partially.

[the PDF](http://gofile.me/2itnX/tQLZVG33C)
is converted into [this SVG](http://gofile.me/2itnX/TGOkZW0Of)

So:
![image](https://user-images.githubusercontent.com/1175751/223747712-1a1e544e-8bfe-4b1f-bae0-d778e5a89641.png)

vs:
![image](https://user-images.githubusercontent.com/1175751/223747804-6dbd2285-ec15-46b5-a910-df473822f590.png)

Any idea what might be wrong?
Any hints what we should look into?

**Comment by gentledepp** [comment]
Upadte: It seems to have something todo with the fact, that the PDF contains transformed text. (mostly rotation)

We "fixed" this by printing the PDF again with the "Microsoft Print to PDF" printer:
![image](https://user-images.githubusercontent.com/1175751/224026447-94318dc3-b320-44a7-9b09-f8dc96937473.png)


The difference seems to be that "Microsoft Print to PDF" replaces the <text> elements with <path> s
Check it out here [Converted with Microsoft Print to PDF](http://gofile.me/2itnX/uprx4Nydw)

**Comment by dmester** [comment]
Thanks for reporting these tricky pdfs! It is really helpful. A fix is available in v0.8.2.
 
Regarding this particular PDF:
	
The glyph widths in embedded fonts are duplicated in two places: in the font itself, and in the PDF metadata. The metadata is used for rendering the PDF on the screen, but the widths in the embedded fonts were exported as-is by PdfToSvg.NET.
 
I have no idea why some PDF producers are causing this kind of corruption inside the fonts, but in version 0.8.2 the lib will overwrite the width data inside the fonts with the data from the PDF.
 
I also noticed the icon in the lower right corner was not extracted. It is a grayscale JPEG. Previous versions of the lib only exported RGB JPEGs, since neither Chrome nor Firefox support CMYK JPEGs. However grayscale JPEGs don't seem to be a problem, so they are now extracted as well.
